---
- name: Daily maintenance tasks
  gather_facts: yes
  gather_subset:
    - "env"
  hosts: localhost
  vars:
    root: "{{ ansible_env.HOME }}"
    luanti: "{{ root }}/.var/app/net.minetest.Minetest/.minetest"
    backup: "{{ root }}/backup"
    world: "world"
    world_dir: "{{ luanti }}/worlds/{{ world }}"
    run_cmd: "flatpak run net.minetest.Minetest"
  tasks:
    - name: Daily backup
      archive:
        path: "{{ world_dir }}"
        dest: "{{ backup }}/luanti_{{ world }}.{{ ansible_date_time.date }}.zip"
        format: zip
      tags:
        - backup
    - name: Save list of mods
      shell: "ls {{ luanti }}/mods > modlist.{{ ansible_date_time.date }}.txt"
      tags:
        - backup
        - mods