---
- name: Execute Python code in Luanti
  gather_facts: yes
  gather_subset:
    - "env"
  hosts: localhost
  vars:
    root: "{{ ansible_env.HOME }}"
    luanti: "{{ root }}/.var/app/net.minetest.Minetest/.minetest"
    backup: "{{ root }}/backup"
    world: "world"
    world_dir: "{{ luanti }}/worlds/{{ world }}"
    run_cmd: "flatpak run net.minetest.Minetest"
    today: "{{ ansible_date_time.date }}"
  tasks:
    - name: Install map tool
      ansible.builtin.git:
        repo:  https://github.com/miney-py/mineysocket.git
        dest: "{{ root }}"